%% rowPlotDemo.m
X = -pi:.1:pi;
X = X';
Ys = {[sin(X),cos(X)];[sin(2*X),cos(2*X)];[sin(3*X),cos(3*X)];[sin(4*X),cos(4*X)]};

rowPlot(X,Ys,...
    'FigureName','demo',...
    'FigureWidth', 1920,...
    'FigureHeight', 800,...
    'FigureMargin', 0.005,...
    'XLabelFontSize', 20,...
    'YLabelFontSize', 20,...
    'TitleFontSize', 20,...
    'LegendFontSize', 20,...
    'AxesFontSize', 18,...
    'title', {'AX1','AX2','AX3','AX4'},...
    'xlim', [-pi pi],...
    'ylim', {[(0.99 * min(Ys{1}(:))) (1.01 * max(Ys{1}(:)))], [(0.99 * min(Ys{2}(:))) (1.01 * max(Ys{2}(:)))],[(0.99 * min(Ys{3}(:))) (1.01 * max(Ys{3}(:)))], [(0.99 * min(Ys{4}(:))) (1.01 * max(Ys{4}(:)))]},...
    'xlabel', 'X',...
    'ylabel', 'Y',...
    'legend', {{'Group_1','Group_2'}, 'Interpreter', 'tex'},...
    'PlotProperties',{'LineWidth', 2, 'Marker', ['+', 'o'], 'MarkerSize', 8, 'Color', ['r', 'b']});
 